<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjspmo3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjspmo3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXjspmo3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXjspmo3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXjspmo3\appProdProjectContainer(array(
    'container.build_hash' => 'Xjspmo3',
    'container.build_id' => '757450c7',
    'container.build_time' => 1516030837,
));
