<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'WCS\CoavBundle\Form\PlaneModelType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/src/WCS/CoavBundle/Form/PlaneModelType.php';

return $this->services['WCS\CoavBundle\Form\PlaneModelType'] = new \WCS\CoavBundle\Form\PlaneModelType();
