<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3a10qvi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3a10qvi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3a10qvi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3a10qvi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3a10qvi\appDevDebugProjectContainer(array(
    'container.build_hash' => '3a10qvi',
    'container.build_id' => '22e6f3ff',
    'container.build_time' => 1516355598,
));
